"""
Generate a larger, deterministic sql/seed.sql for GigTrack.

Run:  python scripts/generate_seed.py
Output: overwrites sql/seed.sql

Deterministic (fixed RNG seed) so the dataset is reproducible across runs and
the Mongo seed (mongo/seed.py) can rely on the same counts/IDs. Designed to
respect the BEFORE INSERT booking trigger: tickets start full and seeded
bookings only ever decrement within availability.

Counts are also mirrored in mongo/seed.py — keep them in sync.
"""
import os
import random

NUM_USERS    = 21      # user_id 1 = admin "macc"
NUM_ARTISTS  = 30
NUM_VENUES   = 15
NUM_CONCERTS = 50

# bcrypt hash of the literal "password" (cost 12), verified.
PW_HASH = "$2b$12$1nWfTl72I7cXuuntYbZCdevCXVSSYW5MCaC3TOxX.j3YXwV4.sv/y"

rng = random.Random(20260530)

GENRES = ["Indie Rock", "R&B", "Post-Punk", "Pop", "Synthwave", "Indie Folk",
          "Hip-Hop", "House", "Jazz", "Metal", "Funk", "Ambient", "K-Pop", "Soul"]
COUNTRIES = ["UK", "USA", "Japan", "Singapore", "Germany", "Canada", "Korea",
             "Australia", "France", "Sweden"]
CITIES = [("Singapore", "Singapore"), ("Kuala Lumpur", "Malaysia"),
          ("Tokyo", "Japan"), ("London", "UK"), ("Seoul", "Korea"),
          ("Sydney", "Australia"), ("Berlin", "Germany"), ("New York", "USA")]

ADJ = ["Midnight", "Velvet", "Neon", "Silver", "Crystal", "Electric", "Golden",
       "Crimson", "Lunar", "Cosmic", "Paper", "Hollow", "Wild", "Quiet", "Glass"]
NOUN = ["Lanterns", "Mango", "Static", "Drift", "Echo", "Tide", "Foxes", "Circuit",
        "Harbour", "Mirage", "Anthem", "Bloom", "Riot", "Parade", "Signal"]


def sql_str(s):
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def main():
    lines = []
    w = lines.append
    w("-- ============================================================")
    w("-- GigTrack — seed data (GENERATED by scripts/generate_seed.py)")
    w("-- Deterministic. Passwords are bcrypt('password'). user_id 1 is admin.")
    w("-- Edit the generator, not this file.")
    w("-- ============================================================\n")

    # ---- users ----
    w("INSERT INTO users (username, email, password_hash, home_city, is_admin) VALUES")
    rows = []
    rows.append(f"  ('macc', 'macc@example.com', '{PW_HASH}', 'Singapore', 1)")
    for i in range(2, NUM_USERS + 1):
        city = rng.choice(CITIES)[0]
        rows.append(f"  ('user{i:02d}', 'user{i:02d}@example.com', '{PW_HASH}', {sql_str(city)}, 0)")
    w(",\n".join(rows) + ";\n")

    # ---- artists ----
    w("INSERT INTO artists (name, genre, country) VALUES")
    rows = []
    used = set()
    for i in range(NUM_ARTISTS):
        while True:
            name = f"{rng.choice(ADJ)} {rng.choice(NOUN)}"
            if name not in used:
                used.add(name)
                break
        rows.append(f"  ({sql_str(name)}, {sql_str(rng.choice(GENRES))}, {sql_str(rng.choice(COUNTRIES))})")
    w(",\n".join(rows) + ";\n")

    # ---- venues ----
    w("INSERT INTO venues (name, city, country, capacity) VALUES")
    rows = []
    for i in range(NUM_VENUES):
        city, country = rng.choice(CITIES)
        rows.append(f"  ({sql_str(f'Hall {i+1:02d} {city}')}, {sql_str(city)}, {sql_str(country)}, {rng.choice([800,1000,1600,2500,4000,5000])})")
    w(",\n".join(rows) + ";\n")

    # ---- concerts ----
    # Dates: today is 2026-05-30. Future = scheduled; past = completed.
    w("INSERT INTO concerts (venue_id, headline_artist_id, title, concert_date, status, base_price) VALUES")
    rows = []
    concert_status = {}
    for cid in range(1, NUM_CONCERTS + 1):
        venue = rng.randint(1, NUM_VENUES)
        artist = rng.randint(1, NUM_ARTISTS)
        future = rng.random() < 0.78
        if future:
            month = rng.choice([6, 7, 8, 9, 10, 11, 12])
            status = "scheduled"
        else:
            month = rng.choice([1, 2, 3, 4, 5])
            status = "completed"
        day = rng.randint(1, 27)
        hour = rng.choice([19, 20, 21])
        date = f"2026-{month:02d}-{day:02d} {hour:02d}:00:00"
        price = rng.choice([55, 65, 70, 75, 88, 95, 110, 120, 140])
        title = f"Tour Stop #{cid}"
        concert_status[cid] = status
        rows.append(f"  ({venue}, {artist}, {sql_str(title)}, '{date}', '{status}', {price}.00)")
    w(",\n".join(rows) + ";\n")

    # ---- concert_artists (headliner + supports) ----
    w("INSERT INTO concert_artists (concert_id, artist_id, slot_order, role) VALUES")
    rows = []
    for cid in range(1, NUM_CONCERTS + 1):
        head = rng.randint(1, NUM_ARTISTS)
        rows.append(f"  ({cid}, {head}, 1, 'headliner')")
        supports = rng.sample(range(1, NUM_ARTISTS + 1), rng.randint(0, 2))
        slot = 2
        for s in supports:
            if s == head:
                continue
            rows.append(f"  ({cid}, {s}, {slot}, 'support')")
            slot += 1
    w(",\n".join(rows) + ";\n")

    # ---- tickets ----
    w("INSERT INTO tickets (concert_id, tier, price, total_seats, available_seats) VALUES")
    rows = []
    ticket_id = 0
    ticket_meta = {}  # ticket_id -> (concert_id, price, total_seats)
    for cid in range(1, NUM_CONCERTS + 1):
        tiers = rng.sample(["GA", "VIP", "Pit", "Balcony"], rng.randint(1, 3))
        for tier in tiers:
            ticket_id += 1
            price = rng.choice([55, 70, 88, 110, 150, 195, 220])
            seats = rng.choice([300, 500, 900, 1500, 2200, 4000])
            ticket_meta[ticket_id] = (cid, price, seats)
            rows.append(f"  ({cid}, {sql_str(tier)}, {price}.00, {seats}, {seats})")
    w(",\n".join(rows) + ";\n")
    num_tickets = ticket_id

    # ---- bookings (trigger decrements seats) ----
    w("INSERT INTO bookings (user_id, ticket_id, quantity, total_price, status, booked_at) VALUES")
    rows = []
    seats_left = {tid: meta[2] for tid, meta in ticket_meta.items()}
    for _ in range(180):
        tid = rng.randint(1, num_tickets)
        if seats_left[tid] < 6:
            continue
        qty = rng.randint(1, 4)
        seats_left[tid] -= qty
        cid, price, _ = ticket_meta[tid]
        uid = rng.randint(1, NUM_USERS)
        total = price * qty
        month = rng.choice([1, 2, 3, 4, 5])
        day = rng.randint(1, 27)
        rows.append(f"  ({uid}, {tid}, {qty}, {total}.00, 'confirmed', '2026-{month:02d}-{day:02d} 12:00:00')")
    w(",\n".join(rows) + ";\n")

    # ---- follows (unique user/artist pairs) ----
    w("INSERT INTO follows (user_id, artist_id) VALUES")
    pairs = set()
    while len(pairs) < 220:
        pairs.add((rng.randint(1, NUM_USERS), rng.randint(1, NUM_ARTISTS)))
    rows = [f"  ({u}, {a})" for u, a in sorted(pairs)]
    w(",\n".join(rows) + ";\n")

    out = os.path.join(os.path.dirname(__file__), "..", "sql", "seed.sql")
    out = os.path.abspath(out)
    with open(out, "w") as fh:
        fh.write("\n".join(lines))
    print(f"Wrote {out}")
    print(f"  users={NUM_USERS} artists={NUM_ARTISTS} venues={NUM_VENUES} "
          f"concerts={NUM_CONCERTS} tickets={num_tickets} bookings≈{len(rows)} follows=220")


if __name__ == "__main__":
    main()
