"""
Generate a larger, deterministic sql/seed.sql for GigTrack.

Run:  python scripts/generate_seed.py
Output: overwrites sql/seed.sql

Deterministic (fixed RNG seed) so the dataset is reproducible across runs and
the Mongo seed (mongo/seed.py) can rely on the same counts/IDs. Designed to
respect the BEFORE INSERT booking trigger: tickets start full and seeded
bookings only ever decrement within availability.

Counts are also mirrored in mongo/seed.py — keep them in sync.
"""
import os
import random

NUM_USERS    = 21      # user_id 1 = admin "macc"
NUM_ARTISTS  = 30
NUM_VENUES   = 15
NUM_CONCERTS = 50

# bcrypt hash of the literal "password" (cost 12), verified.
PW_HASH = "$2b$12$1nWfTl72I7cXuuntYbZCdevCXVSSYW5MCaC3TOxX.j3YXwV4.sv/y"

rng = random.Random(20260530)

GENRES = ["Indie Rock", "R&B", "Post-Punk", "Pop", "Synthwave", "Indie Folk",
          "Hip-Hop", "House", "Jazz", "Metal", "Funk", "Ambient", "K-Pop", "Soul"]
COUNTRIES = ["UK", "USA", "Japan", "Singapore", "Germany", "Canada", "Korea",
             "Australia", "France", "Sweden"]
CITIES = [("Singapore", "Singapore"), ("Kuala Lumpur", "Malaysia"),
          ("Tokyo", "Japan"), ("London", "UK"), ("Seoul", "Korea"),
          ("Sydney", "Australia"), ("Berlin", "Germany"), ("New York", "USA")]

# Real-world venues (name, city, country, capacity). All ASCII to avoid any
# charset surprises. We sample NUM_VENUES of these.
VENUE_POOL = [
    ("National Stadium",          "Singapore",    "Singapore", 55000),
    ("Singapore Indoor Stadium",  "Singapore",    "Singapore", 12000),
    ("The Star Theatre",          "Singapore",    "Singapore", 5000),
    ("Esplanade Concert Hall",    "Singapore",    "Singapore", 1600),
    ("Axiata Arena",              "Kuala Lumpur", "Malaysia",  16000),
    ("Zepp Kuala Lumpur",         "Kuala Lumpur", "Malaysia",  2500),
    ("Tokyo Dome",                "Tokyo",        "Japan",     55000),
    ("Nippon Budokan",            "Tokyo",        "Japan",     14000),
    ("Zepp DiverCity",            "Tokyo",        "Japan",     2500),
    ("The O2 Arena",              "London",       "UK",        20000),
    ("OVO Arena Wembley",         "London",       "UK",        12500),
    ("O2 Academy Brixton",        "London",       "UK",        4900),
    ("KSPO Dome",                 "Seoul",        "Korea",     15000),
    ("Gocheok Sky Dome",          "Seoul",        "Korea",     16000),
    ("Qudos Bank Arena",          "Sydney",       "Australia", 21000),
    ("Sydney Opera House",        "Sydney",       "Australia", 5700),
    ("Mercedes-Benz Arena",       "Berlin",       "Germany",   17000),
    ("Columbiahalle",             "Berlin",       "Germany",   3500),
    ("Madison Square Garden",     "New York",     "USA",       20000),
    ("Barclays Center",           "New York",     "USA",       19000),
    ("Radio City Music Hall",     "New York",     "USA",       6000),
]

ADJ = ["Midnight", "Velvet", "Neon", "Silver", "Crystal", "Electric", "Golden",
       "Crimson", "Lunar", "Cosmic", "Paper", "Hollow", "Wild", "Quiet", "Glass"]
NOUN = ["Lanterns", "Mango", "Static", "Drift", "Echo", "Tide", "Foxes", "Circuit",
        "Harbour", "Mirage", "Anthem", "Bloom", "Riot", "Parade", "Signal"]
TOURS = ["World Tour 2026", "Live 2026", "Asia Tour", "The Neon Nights Tour",
         "Homecoming Live", "Stadium Tour 2026", "Acoustic Sessions",
         "The Comeback Tour", "Aftermath Tour", "Midnight Run Tour"]


def sql_str(s):
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def main():
    lines = []
    w = lines.append
    w("-- ============================================================")
    w("-- GigTrack - seed data (GENERATED by scripts/generate_seed.py)")
    w("-- Deterministic. Passwords are bcrypt('password'). user_id 1 is admin.")
    w("-- Edit the generator, not this file.")
    w("-- ============================================================")
    w("SET NAMES utf8mb4;\n")

    # ---- users ----
    w("INSERT INTO users (username, email, password_hash, home_city, is_admin) VALUES")
    rows = []
    rows.append(f"  ('macc', 'macc@example.com', '{PW_HASH}', 'Singapore', 1)")
    for i in range(2, NUM_USERS + 1):
        city = rng.choice(CITIES)[0]
        rows.append(f"  ('user{i:02d}', 'user{i:02d}@example.com', '{PW_HASH}', {sql_str(city)}, 0)")
    w(",\n".join(rows) + ";\n")

    # ---- artists ----
    w("INSERT INTO artists (name, genre, country) VALUES")
    rows = []
    artist_names = []           # index 0 -> artist_id 1
    used = set()
    for i in range(NUM_ARTISTS):
        while True:
            name = f"{rng.choice(ADJ)} {rng.choice(NOUN)}"
            if name not in used:
                used.add(name)
                break
        artist_names.append(name)
        rows.append(f"  ({sql_str(name)}, {sql_str(rng.choice(GENRES))}, {sql_str(rng.choice(COUNTRIES))})")
    w(",\n".join(rows) + ";\n")

    # ---- venues (real venues sampled from the pool) ----
    w("INSERT INTO venues (name, city, country, capacity) VALUES")
    rows = []
    venue_cities = []           # index 0 -> venue_id 1
    chosen_venues = rng.sample(VENUE_POOL, min(NUM_VENUES, len(VENUE_POOL)))
    for name, city, country, cap in chosen_venues:
        venue_cities.append(city)
        rows.append(f"  ({sql_str(name)}, {sql_str(city)}, {sql_str(country)}, {cap})")
    w(",\n".join(rows) + ";\n")

    # ---- concerts ----
    # Dates: today is 2026-05-30. Future = scheduled; past = completed.
    # The concert title is built from the HEADLINING ARTIST (not a generic tour
    # number), and that same artist is slot 1 in concert_artists below.
    w("INSERT INTO concerts (venue_id, headline_artist_id, title, concert_date, status, base_price) VALUES")
    rows = []
    concert_head = {}           # concert_id -> headliner artist_id
    for cid in range(1, NUM_CONCERTS + 1):
        venue = rng.randint(1, NUM_VENUES)
        artist = rng.randint(1, NUM_ARTISTS)
        concert_head[cid] = artist
        future = rng.random() < 0.78
        if future:
            month = rng.choice([6, 7, 8, 9, 10, 11, 12])
            status = "scheduled"
        else:
            month = rng.choice([1, 2, 3, 4, 5])
            status = "completed"
        day = rng.randint(1, 27)
        hour = rng.choice([19, 20, 21])
        date = f"2026-{month:02d}-{day:02d} {hour:02d}:00:00"
        price = rng.choice([55, 65, 70, 75, 88, 95, 110, 120, 140])
        title = f"{artist_names[artist - 1]} - {rng.choice(TOURS)}"
        rows.append(f"  ({venue}, {artist}, {sql_str(title)}, '{date}', '{status}', {price}.00)")
    w(",\n".join(rows) + ";\n")

    # ---- concert_artists (headliner + supports) ----
    # Slot 1 MUST equal concerts.headline_artist_id so the lineup is consistent.
    w("INSERT INTO concert_artists (concert_id, artist_id, slot_order, role) VALUES")
    rows = []
    for cid in range(1, NUM_CONCERTS + 1):
        head = concert_head[cid]
        rows.append(f"  ({cid}, {head}, 1, 'headliner')")
        supports = rng.sample(range(1, NUM_ARTISTS + 1), rng.randint(0, 2))
        slot = 2
        for s in supports:
            if s == head:
                continue
            rows.append(f"  ({cid}, {s}, {slot}, 'support')")
            slot += 1
    w(",\n".join(rows) + ";\n")

    # ---- tickets ----
    w("INSERT INTO tickets (concert_id, tier, price, total_seats, available_seats) VALUES")
    rows = []
    ticket_id = 0
    ticket_meta = {}  # ticket_id -> (concert_id, price, total_seats)
    for cid in range(1, NUM_CONCERTS + 1):
        tiers = rng.sample(["GA", "VIP", "Pit", "Balcony"], rng.randint(1, 3))
        for tier in tiers:
            ticket_id += 1
            price = rng.choice([55, 70, 88, 110, 150, 195, 220])
            seats = rng.choice([300, 500, 900, 1500, 2200, 4000])
            ticket_meta[ticket_id] = (cid, price, seats)
            rows.append(f"  ({cid}, {sql_str(tier)}, {price}.00, {seats}, {seats})")
    w(",\n".join(rows) + ";\n")
    num_tickets = ticket_id

    # ---- bookings (trigger decrements seats) ----
    w("INSERT INTO bookings (user_id, ticket_id, quantity, total_price, status, booked_at) VALUES")
    rows = []
    seats_left = {tid: meta[2] for tid, meta in ticket_meta.items()}
    for _ in range(180):
        tid = rng.randint(1, num_tickets)
        if seats_left[tid] < 6:
            continue
        qty = rng.randint(1, 4)
        seats_left[tid] -= qty
        cid, price, _ = ticket_meta[tid]
        uid = rng.randint(1, NUM_USERS)
        total = price * qty
        month = rng.choice([1, 2, 3, 4, 5])
        day = rng.randint(1, 27)
        rows.append(f"  ({uid}, {tid}, {qty}, {total}.00, 'confirmed', '2026-{month:02d}-{day:02d} 12:00:00')")
    w(",\n".join(rows) + ";\n")

    # ---- follows (unique user/artist pairs) ----
    w("INSERT INTO follows (user_id, artist_id) VALUES")
    pairs = set()
    while len(pairs) < 220:
        pairs.add((rng.randint(1, NUM_USERS), rng.randint(1, NUM_ARTISTS)))
    rows = [f"  ({u}, {a})" for u, a in sorted(pairs)]
    w(",\n".join(rows) + ";\n")

    out = os.path.join(os.path.dirname(__file__), "..", "sql", "seed.sql")
    out = os.path.abspath(out)
    with open(out, "w") as fh:
        fh.write("\n".join(lines))
    print(f"Wrote {out}")
    print(f"  users={NUM_USERS} artists={NUM_ARTISTS} venues={NUM_VENUES} "
          f"concerts={NUM_CONCERTS} tickets={num_tickets} bookings≈{len(rows)} follows=220")


if __name__ == "__main__":
    main()
